name: Build and Push

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "src/**/__tests__/**"
      - "src/**/__mocks__/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  version:
    name: Determine Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.determine-version.outputs.version }}
    steps:
      - name: Checkout code from target branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install nbgv
        shell: bash
        run: dotnet tool install --tool-path . nbgv

      - name: Determine version
        id: determine-version
        shell: bash
        run: |
          cd src
          AssemblyInfoVersion=$(nbgv get-version -v AssemblyInformationalVersion)
          echo "version=${AssemblyInfoVersion/+/-}" >> $GITHUB_OUTPUT
          echo "Version:" ${AssemblyInfoVersion/+/-}

  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run test

  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    needs: [version, ci]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Generate version
        run: echo "container_version=gunsmithbot:${{ needs.version.outputs.version }}" >> $GITHUB_ENV

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/chargeflux/gunsmithbot/${{ env.container_version }}
          file: ./Dockerfile
          context: .
