name: Build and Push

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  version:
    name: Determine Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.determine-version.outputs.version }}
    steps:
      - name: Checkout code from target branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install nbgv
        shell: bash
        run: dotnet tool install --tool-path . nbgv

      - name: Determine version
        id: determine-version
        shell: bash
        run: |
          cd src
          AssemblyInfoVersion=$(nbgv get-version -v AssemblyInformationalVersion)
          echo "::set-output name=version::${AssemblyInfoVersion/+/-}"
          echo "Version:" ${AssemblyInfoVersion/+/-}

  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    needs: [version, ci]
    outputs:
      version: ${{ steps.container_version.outputs.container_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Generate version
        id: container_version
        shell: pwsh
        run: |
          echo "::set-output name=container_version::gunsmithbot:${{ needs.version.outputs.version }}"

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/chargeflux/gunsmithbot/${{ steps.container_version.outputs.container_version }}
          file: ./Dockerfile
          context: .
